#
# Makefile
#
# Autor: H.Drachenfels
# Erstellt am: 27.2.2014
#

CC=gcc
CFLAGS = -g -W -Wall -ansi -pedantic

TARGET = aufgabe4

.PHONY: all clean

all: $(TARGET)

clean:
	$(RM) $(TARGET) $(TARGET).o

