#
# Makefile
#
# Autor: H.Drachenfels
# Erstellt am: 25.2.2014
#

CC=gcc -g
CFLAGS = -W -Wall -ansi -pedantic

TARGET = filesize filecopy

.PHONY: all clean

all: $(TARGET)

clean:
	$(RM) $(TARGET) $(TARGET).o
